module.exports = {
  combat: [
    {
      key: "vitality",
      name: "Vitality",
      attributes: ["might", "resolve"],
      summary: "Staying alive through blood loss, impact, poison, and punishment.",
      examples: ["resisting injury", "holding consciousness", "surviving brutal force"],
    },
    {
      key: "guard",
      name: "Guard",
      attributes: ["agility", "resolve"],
      summary: "Defending against direct attacks, forced movement, and immediate danger.",
      examples: ["blocking a strike", "holding cover", "resisting knockback"],
    },
    {
      key: "initiative",
      name: "Initiative",
      attributes: ["agility", "instinct"],
      summary: "Acting first when violence, disaster, or opportunity breaks open.",
      examples: ["opening tempo", "ambush response", "seizing a fleeting chance"],
    },
    {
      key: "skirmish",
      name: "Skirmish",
      attributes: ["might", "agility"],
      summary: "Fast violence, dueling tempo, and closing the gap before someone can react.",
      examples: ["boarding actions", "sword duels", "aggressive chases"],
    },
    {
      key: "precision",
      name: "Precision",
      attributes: ["agility", "wit"],
      summary: "Aim, control, and exact action under pressure.",
      examples: ["marksmanship", "fine sabotage", "surgical strikes"],
    },
    {
      key: "reflex",
      name: "Reflex",
      attributes: ["agility", "instinct"],
      summary: "Pure reaction speed, evasive motion, and split-second positioning.",
      examples: ["dodging ambushes", "quickdraw contests", "reactive movement"],
    },
    {
      key: "tactics",
      name: "Tactics",
      attributes: ["wit", "resolve"],
      summary: "Discipline, planning, and making the smart move when panic would be easier.",
      examples: ["battle plans", "coordinating allies", "staying sharp in chaos"],
    },
    {
      key: "endurance",
      name: "Endurance",
      attributes: ["might", "resolve"],
      summary: "Lasting through fatigue, pain, deprivation, and repeated strain.",
      examples: ["forced marches", "wound shock", "holding a line"],
    },
  ],
  social: [
    {
      key: "grace",
      name: "Grace",
      attributes: ["spirit", "resolve"],
      summary: "Poise, diplomacy, trust-building, and holding yourself with calm authority.",
      examples: ["persuasion", "court etiquette", "soft leadership"],
    },
    {
      key: "guile",
      name: "Guile",
      attributes: ["wit", "spirit"],
      summary: "Misdirection, layered lies, and steering attention away from the truth.",
      examples: ["deception", "secret negotiations", "double meanings"],
    },
    {
      key: "pressure",
      name: "Pressure",
      attributes: ["might", "resolve"],
      summary: "Command presence, intimidation, and forcing someone to bend under your will.",
      examples: ["threats", "hard bargaining", "battlefield authority"],
    },
    {
      key: "conviction",
      name: "Conviction",
      attributes: ["might", "spirit"],
      summary: "The force of soul behind a declaration, oath, prayer, or war cry.",
      examples: ["rallying with zeal", "prophetic declarations", "sacred menace"],
    },
    {
      key: "flourish",
      name: "Flourish",
      attributes: ["agility", "spirit"],
      summary: "Style, magnetism, and performative grace that turns motion into influence.",
      examples: ["performance", "ceremonial display", "seductive presence"],
    },
    {
      key: "presence",
      name: "Presence",
      attributes: ["spirit", "might"],
      summary: "Commanding attention before anyone has agreed to listen.",
      examples: ["entering a hostile room", "projecting authority", "drawing every eye"],
    },
    {
      key: "composure",
      name: "Composure",
      attributes: ["resolve", "wit"],
      summary: "Keeping your face, judgment, and voice steady under social fire.",
      examples: ["resisting bait", "court pressure", "high-stakes negotiation"],
    },
  ],
  exploration: [
    {
      key: "pursuit",
      name: "Pursuit",
      attributes: ["might", "instinct"],
      summary: "Predatory momentum, relentless tracking, and running something down.",
      examples: ["hunting prey", "survival chases", "pressing an advantage through wilderness"],
    },
    {
      key: "balance",
      name: "Balance",
      attributes: ["agility", "resolve"],
      summary: "Control under stress, footwork, and staying steady when the world lurches.",
      examples: ["rope bridges", "storm decks", "keeping footing under fire"],
    },
    {
      key: "sense",
      name: "Sense",
      attributes: ["wit", "instinct"],
      summary: "Reading danger, seeing patterns, and noticing what others miss.",
      examples: ["trap reading", "weather signs", "navigational judgment"],
    },
    {
      key: "nerve",
      name: "Nerve",
      attributes: ["resolve", "instinct"],
      summary: "Staying sharp in danger, trusting your gut, and not breaking when fear arrives first.",
      examples: ["fear resistance", "disaster response", "making the call under stress"],
    },
    {
      key: "survival",
      name: "Survival",
      attributes: ["resolve", "instinct"],
      summary: "Keeping yourself and others alive when the world stops cooperating.",
      examples: ["finding shelter", "rationing supplies", "weathering exposure"],
    },
    {
      key: "navigation",
      name: "Navigation",
      attributes: ["wit", "instinct"],
      summary: "Finding the route, reading currents, and arriving before the danger does.",
      examples: ["sea charts", "island routes", "storm paths"],
    },
    {
      key: "scouting",
      name: "Scouting",
      attributes: ["agility", "instinct"],
      summary: "Moving ahead, finding trouble, and returning with useful truth.",
      examples: ["reconnaissance", "hidden approaches", "enemy movement"],
    },
    {
      key: "adaptation",
      name: "Adaptation",
      attributes: ["wit", "resolve"],
      summary: "Changing plans cleanly when conditions turn strange, hostile, or impossible.",
      examples: ["improvised routes", "new hazards", "salvaged plans"],
    },
  ],
  utility: [
    {
      key: "leverage",
      name: "Leverage",
      attributes: ["might", "wit"],
      summary: "Using strength intelligently and forcing the environment to cooperate.",
      examples: ["forcing a hatch", "improvised siege work", "machine jams"],
    },
    {
      key: "patch",
      name: "Patch",
      attributes: ["wit", "resolve"],
      summary: "Restoring people, hulls, systems, or seals before collapse spreads.",
      examples: ["field medicine", "hull repair", "stabilizing a failing device"],
    },
    {
      key: "breach",
      name: "Breach",
      attributes: ["might", "wit"],
      summary: "Opening what was built to stay shut.",
      examples: ["doors", "safes", "bulkheads", "institutional barriers"],
    },
    {
      key: "salvage",
      name: "Salvage",
      attributes: ["wit", "instinct"],
      summary: "Finding value, secrets, and usable components in dangerous ruin.",
      examples: ["wreck picking", "component recovery", "battlefield spoils"],
    },
    {
      key: "signal",
      name: "Signal",
      attributes: ["wit", "spirit"],
      summary: "Sending, intercepting, spoofing, or interpreting communication.",
      examples: ["coded messages", "flare timing", "relic resonance signals"],
    },
    {
      key: "secure",
      name: "Secure",
      attributes: ["resolve", "might"],
      summary: "Locking down people, cargo, rooms, evidence, and exits.",
      examples: ["containment", "restraints", "holding a perimeter"],
    },
    {
      key: "fabricate",
      name: "Fabricate",
      attributes: ["wit", "agility"],
      summary: "Assembling decoys, tools, charges, papers, or stopgap infrastructure.",
      examples: ["fake documents", "field tools", "quick rigging"],
    },
    {
      key: "broker",
      name: "Broker",
      attributes: ["wit", "resolve"],
      summary: "Moving goods, permits, access, and favors through the right hands.",
      examples: ["black markets", "guild access", "quiet introductions"],
    },
  ],
  arcane: [
    {
      key: "focus",
      name: "Focus",
      attributes: ["spirit", "resolve"],
      summary: "Mental stability, magical control, and resistance against strain.",
      examples: ["concentration", "ritual pressure", "resisting backlash"],
    },
    {
      key: "attunement",
      name: "Attunement",
      attributes: ["spirit", "instinct"],
      summary: "Sensitivity to spirits, relic resonance, omens, and the unseen pulse of a place.",
      examples: ["reading relics", "spirit contact", "feeling corruption in the air"],
    },
    {
      key: "invoke",
      name: "Invoke",
      attributes: ["spirit", "resolve"],
      summary: "Calling a force, storm memory, ancestor current, or bound entity into action.",
      examples: ["ritual force", "spirit aid", "dangerous miracles"],
    },
    {
      key: "ward",
      name: "Ward",
      attributes: ["spirit", "resolve"],
      summary: "Setting protections against intrusion, panic, backlash, and corruption.",
      examples: ["spirit barriers", "safe circles", "counter-curses"],
    },
    {
      key: "unravel",
      name: "Unravel",
      attributes: ["spirit", "wit"],
      summary: "Breaking curses, exposing false miracles, and pulling hostile magic apart.",
      examples: ["curse breaking", "dispelling", "revealing occult fraud"],
    },
    {
      key: "corruption",
      name: "Corruption",
      attributes: ["resolve", "spirit"],
      summary: "Resisting, containing, or deliberately channeling tainted power.",
      examples: ["corruption saves", "forbidden relics", "containing spiritual rot"],
    },
    {
      key: "omen",
      name: "Omen",
      attributes: ["spirit", "instinct"],
      summary: "Interpreting signs, echoes, dreams, and warnings from unseen currents.",
      examples: ["prophecy", "storm signs", "ancestral warnings"],
    },
    {
      key: "bind",
      name: "Bind",
      attributes: ["spirit", "wit"],
      summary: "Holding a spirit, oath, effect, or anomaly in a controlled state.",
      examples: ["spirit binding", "ritual seals", "holding anomalies"],
    },
  ],
};
