module.exports = {
  combat: [
    {
      id: "board",
      name: "Board",
      verb: "Close distance through chaos and claim contested space.",
      linkedAttributes: ["might", "agility"],
    },
    {
      id: "shoot",
      name: "Shoot",
      verb: "Land precise ranged fire under pressure.",
      linkedAttributes: ["agility", "wit"],
    },
    {
      id: "cut",
      name: "Cut",
      verb: "Fight in reach, tear openings, and punish exposed targets.",
      linkedAttributes: ["might", "agility"],
    },
    {
      id: "brace",
      name: "Brace",
      verb: "Absorb impact, hold ground, and turn momentum against an attack.",
      linkedAttributes: ["resolve", "might"],
    },
    {
      id: "feint",
      name: "Feint",
      verb: "Force a mistake and exploit a false read.",
      linkedAttributes: ["agility", "spirit"],
    },
    {
      id: "suppress",
      name: "Suppress",
      verb: "Deny action, lock lanes, and make movement costly.",
      linkedAttributes: ["wit", "resolve"],
    },
  ],
  social: [
    {
      id: "bargain",
      name: "Bargain",
      verb: "Trade leverage, favors, and concessions for a workable deal.",
      linkedAttributes: ["wit", "resolve"],
    },
    {
      id: "command",
      name: "Command",
      verb: "Issue direction that people obey because resisting would cost them.",
      linkedAttributes: ["might", "resolve"],
    },
    {
      id: "deceive",
      name: "Deceive",
      verb: "Sell a lie, hide the real goal, or bury the obvious angle.",
      linkedAttributes: ["wit", "spirit"],
    },
    {
      id: "read",
      name: "Read",
      verb: "Pull motives, pressure points, and concealed intentions out of a scene.",
      linkedAttributes: ["wit", "instinct"],
    },
    {
      id: "perform",
      name: "Perform",
      verb: "Control attention through ceremony, style, rhythm, and emotional timing.",
      linkedAttributes: ["agility", "spirit"],
    },
    {
      id: "threaten",
      name: "Threaten",
      verb: "Make the consequences vivid enough that surrender feels rational.",
      linkedAttributes: ["might", "resolve"],
    },
  ],
  exploration: [
    {
      id: "navigate",
      name: "Navigate",
      verb: "Chart routes, interpret currents, and get people somewhere alive.",
      linkedAttributes: ["wit", "instinct"],
    },
    {
      id: "scout",
      name: "Scout",
      verb: "Find safe lines, useful details, and hidden trouble before it finds you.",
      linkedAttributes: ["agility", "instinct"],
    },
    {
      id: "track",
      name: "Track",
      verb: "Follow signs, pressure patterns, and material traces.",
      linkedAttributes: ["might", "instinct"],
    },
    {
      id: "endure",
      name: "Endure",
      verb: "Survive deprivation, weather, terror, and exhaustion.",
      linkedAttributes: ["resolve", "instinct"],
    },
    {
      id: "climb",
      name: "Climb",
      verb: "Move vertically through wreckage, cliffs, rigging, and towers.",
      linkedAttributes: ["might", "agility"],
    },
    {
      id: "dive",
      name: "Dive",
      verb: "Operate in flooded, submerged, or pressure-heavy spaces.",
      linkedAttributes: ["resolve", "agility"],
    },
  ],
  utility: [
    {
      id: "jury-rig",
      name: "Jury-Rig",
      verb: "Make broken gear work long enough to matter.",
      linkedAttributes: ["wit", "might"],
    },
    {
      id: "patch",
      name: "Patch",
      verb: "Restore people, hulls, systems, or seals before collapse spreads.",
      linkedAttributes: ["wit", "resolve"],
    },
    {
      id: "breach",
      name: "Breach",
      verb: "Force doors, safes, bulkheads, and institutional barriers open.",
      linkedAttributes: ["might", "wit"],
    },
    {
      id: "salvage",
      name: "Salvage",
      verb: "Strip value, secrets, and usable components from dangerous places.",
      linkedAttributes: ["wit", "instinct"],
    },
    {
      id: "signal",
      name: "Signal",
      verb: "Send, intercept, spoof, or interpret coded communication.",
      linkedAttributes: ["wit", "spirit"],
    },
    {
      id: "stabilize",
      name: "Stabilize",
      verb: "Prevent panic, collapse, bleeding, overload, or riot escalation.",
      linkedAttributes: ["resolve", "wit"],
    },
    {
      id: "secure",
      name: "Secure",
      verb: "Lock down people, cargo, rooms, evidence, and exits.",
      linkedAttributes: ["resolve", "might"],
    },
    {
      id: "calibrate",
      name: "Calibrate",
      verb: "Tune engines, scopes, rituals, or sensors for a precise result.",
      linkedAttributes: ["wit", "agility"],
    },
    {
      id: "fabricate",
      name: "Fabricate",
      verb: "Assemble decoys, tools, charges, papers, or stopgap infrastructure.",
      linkedAttributes: ["wit", "agility"],
    },
    {
      id: "broker",
      name: "Broker",
      verb: "Move goods, permits, access, and quiet favors through the right hands.",
      linkedAttributes: ["wit", "resolve"],
    },
  ],
  arcane: [
    {
      id: "attune",
      name: "Attune",
      verb: "Sense resonance, hidden currents, and relic mood.",
      linkedAttributes: ["spirit", "instinct"],
    },
    {
      id: "invoke",
      name: "Invoke",
      verb: "Call a force, storm memory, ancestor current, or bound entity into action.",
      linkedAttributes: ["spirit", "resolve"],
    },
    {
      id: "bind",
      name: "Bind",
      verb: "Hold a spirit, oath, effect, or anomaly in a controlled state.",
      linkedAttributes: ["spirit", "wit"],
    },
    {
      id: "ward",
      name: "Ward",
      verb: "Set protections against intrusion, panic, backlash, and corruption.",
      linkedAttributes: ["spirit", "resolve"],
    },
    {
      id: "sift",
      name: "Sift",
      verb: "Read echoes, omens, and residue left behind by power.",
      linkedAttributes: ["spirit", "wit"],
    },
    {
      id: "unravel",
      name: "Unravel",
      verb: "Break curses, expose false miracles, and pull hostile magic apart.",
      linkedAttributes: ["spirit", "instinct"],
    },
  ],
};
